### ISSUE TITLE
prompt for different tools

### ISSUE THREAD

**Issue by dmgerman** [dspinellis/ai-cli-lib#11]
The [prompt] section in the configuration is used for all tools.

Permit a different prompt for different tools. I think the most flexible way is to have an environment variable that can be set before running the program. This way the prompt can be configured per run for the same tool. For example, for SQLite, the prompt can be set for different databases. By default, the configuration file prompt would be used.

**Comment by dspinellis** [comment]
Definitely an `AI_CLI_LIB_PROMPT` environment variable A per-command prompt configuration could also be useful.

**Comment by dspinellis** [comment]
This has now been implemented via environment variables and program-specific `system` and `context` prompt configuration options.
