### ISSUE TITLE
OpenAI API call failed: Unsupported protocol

### ISSUE THREAD

**Issue by ambitiousCC** [dspinellis/ai-cli-lib#12]
details: when i attach ctrlX then a, it says:
<img width="321" alt="Snipaste_2023-11-20_16-02-47" src="https://github.com/dspinellis/ai-cli-lib/assets/45097033/1f81987d-356b-455c-bdfb-61b7b5abd819">

* this is my config file
<img width="865" alt="Snipaste_2023-11-20_16-00-58" src="https://github.com/dspinellis/ai-cli-lib/assets/45097033/b16d68b7-d628-4c50-ae7c-70d7b3ef57d2">

**Comment by dspinellis** [comment]
Are you behind a firewall?  Can you please set the `OPENAI_API_KEY` variable and try the following command?

```
curl https://api.openai.com/v1/engines/davinci/completions \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "prompt": "I can list files on Unix by running ",
    "max_tokens": 50
  }' 
```

**Comment by dspinellis** [comment]
No response after three weeks. Closing.
