### ISSUE TITLE
llama.cpp did not provide a suitable response.

### ISSUE THREAD

**Issue by rizitis** [dspinellis/ai-cli-lib#3]
Hello, I m new to AI... and maybe something in my setup is not correct. 
When I hit ^X+a I got this
 ```
llama.cpp did not provide a suitable response.
```
I m on Slackware current.

**Comment by dspinellis** [comment]
Are you running a llama.cpp server? What happens when you query your server through _curl_ as shown below?
```bash
curl --request POST --url http://localhost:8080/completion --header "Content-Type: application/json" --data '{ "prompt": "The capital of Germany is Berlin. The capital of Greece is "}'
```

**Comment by rizitis** [comment]
this is the ouput: `{"content":"‎Athens.\nThe most populous city in the world is Tokyo, Japan.","generation_settings":{"frequency_penalty":0.0,"grammar":"","ignore_eos":false,"logit_bias":[],"mirostat":0,"mirostat_eta":0.10000000149011612,"mirostat_tau":5.0,"model":"models/llama-2-13b-chat/orca_mini_v3_7b.Q8_0.gguf","n_ctx":32768,"n_keep":0,"n_predict":-1,"n_probs":0,"penalize_nl":true,"presence_penalty":0.0,"repeat_last_n":64,"repeat_penalty":1.100000023841858,"seed":4294967295,"stop":[],"stream":false,"temp":0.800000011920929,"tfs_z":1.0,"top_k":40,"top_p":0.949999988079071,"typical_p":1.0},"model":"models/llama-2-13b-chat/orca_mini_v3_7b.Q8_0.gguf","prompt":"The capital of Germany is Berlin. The capital of Greece is ","stop":true,"stopped_eos":true,"stopped_limit":false,"stopped_word":false,"stopping_word":"","timings":{"predicted_ms":2345.516,"predicted_n":19,"predicted_per_second":8.10056294649024,"predicted_per_token_ms":123.44821052631579,"prompt_ms":854.229,"prompt_n":14,"prompt_per_second":16.389047901675077,"prompt_per_token_ms":61.016357142857146},"tokens_cached":33,"tokens_evaluated":14,"tokens_predicted":20,"truncated":false`

**Comment by rizitis** [comment]
my ~/.aicliconfig is: `[prompt]
system = You are an assistant who provides executable commands for the %s command-line interface. You only provide the requested command on a single line, without any explanations, hints or other adornments. Stop providing output after the providing the requested command. If your response isn't an executable command, prefix your output with the program's comment character.
context = 3

[openai]
endpoint = https://api.openai.com/v1/chat/completions
model = gpt-3.5-turbo
; The following is more capable, but requires having an established
; payment relationship
; model = gpt-4
temperature = 0.7
; User-specific: add it in a local protected file
; key = bla-bla12345xxxxxxx

[llamacpp]
endpoint = http://localhost:8080/completion


; Key bindings
[binding]
vi = V
emacs = \C-xa

; Multishot command-specific prompts
[prompt-gdb]
user-1 = Disable breakpoint number 4
assistant-1 = delete 4
user-2 = break on line 67 of foo.cpp when flag is false,
assistant-3 = break foo.cpp:67 if !flag

[prompt-bash]
user-1 = List files in current directory
assistant-1 = ls
user-2 = How many JavaScript files in the current directory contain the word bar?
assistant-2 = grep -lw bar *.js | wc -l
user-3 = xyzzy
assistant-3 = # Sorry I can't help.

[prompt-sqlite3]
user-1 = Show available tables
assistant-1 = .tables
user-2 = Show average of grade in table students
assistant-2 = SELECT AVG(grade) FROM students;
user-3 = xyzzy
assistant-3 = -- Sorry I can't help.

[general]
api=llamacpp
api=openai`
I can speak in localohost via browser with llama.cpp bot
![Screenshot from 2023-09-16 03-14-10](https://github.com/dspinellis/ai-cli-lib/assets/412135/5a699096-7a94-4d11-b27f-49627dd93602)

**Comment by dspinellis** [comment]
Ah, excellent! I thought you had misconfigured something. Then the other possibility is that llama.cpp actually did not provide a suitable response, due to your prompt or the small model limitations. Can you please enable logging and also try a couple more prompts?

```ini
[general]
logfile=ai-cli.log
```

**Comment by rizitis** [comment]
Ok after all these days I just realize that:
I cant sing in from cli for any reason in OpenAI with my keys.
So I think case is closed, its the OpenAI who dont like me or my system... 
I will not try more with OpenAI, even GPT4All fails to connect me ONLY with OpenAI services... 
IF you agree close this issue, as is not ai-cli-lib issue. 
Thank you for everything :)
